//
//  CountriesList.swift
//  Winston-PromPlanner
//
//  Created by Winston Yang on 2023-10-24.
//

import Foundation

struct DropDownMenu: Identifiable, Hashable {
    let id = UUID().uuidString
    let option: String
 
}

extension DropDownMenu {
    static let testSingleCountry: DropDownMenu = DropDownMenu(option: "United States of America")
    static let testAllCountry: [DropDownMenu] = [
        DropDownMenu(option: "Afghanistan"),
        DropDownMenu(option: "Albania"),
        DropDownMenu(option: "Algeria"),
        DropDownMenu(option: "Andorra"),
        DropDownMenu(option: "Angola"),
        DropDownMenu(option: "Antigua and Barbuda"),
        DropDownMenu(option: "Argentina"),
        DropDownMenu(option: "Armenia"),
        DropDownMenu(option: "Australia"),
        DropDownMenu(option: "Austria"),
        DropDownMenu(option: "Azerbaijan"),
        DropDownMenu(option: "Bahamas"),
        DropDownMenu(option: "Bahrain"),
        DropDownMenu(option: "Bangladesh"),
        DropDownMenu(option: "Barbados"),
        DropDownMenu(option: "Belarus"),
        DropDownMenu(option: "Belgium"),
        DropDownMenu(option: "Belize"),
        DropDownMenu(option: "Benin"),
        DropDownMenu(option: "Bhutan"),
        DropDownMenu(option: "Bolivia"),
        DropDownMenu(option: "Bosnia and Herzegovina"),
        DropDownMenu(option: "Botswana"),
        DropDownMenu(option: "Brazil"),
        DropDownMenu(option: "Brunei"),
        DropDownMenu(option: "Bulgaria"),
        DropDownMenu(option: "Burkina Faso"),
        DropDownMenu(option: "Burundi"),
        DropDownMenu(option: "Cabo Verde"),
        DropDownMenu(option: "Cambodia"),
        DropDownMenu(option: "Cameroon"),
        DropDownMenu(option: "Canada"),
        DropDownMenu(option: "Central African Republic"),
        DropDownMenu(option: "Chad"),
        DropDownMenu(option: "Chile"),
        DropDownMenu(option: "China"),
        DropDownMenu(option: "Colombia"),
        DropDownMenu(option: "Comoros"),
        DropDownMenu(option: "Congo"),
        DropDownMenu(option: "Costa Rica"),
        DropDownMenu(option: "Croatia"),
        DropDownMenu(option: "Cuba"),
        DropDownMenu(option: "Cyprus"),
        DropDownMenu(option: "Czech Republic"),
        DropDownMenu(option: "Democratic Republic of the Congo"),
        DropDownMenu(option: "Denmark"),
        DropDownMenu(option: "Djibouti"),
        DropDownMenu(option: "Dominica"),
        DropDownMenu(option: "Dominican Republic"),
        DropDownMenu(option: "East Timor (Timor-Leste)"),
        DropDownMenu(option: "Ecuador"),
        DropDownMenu(option: "Egypt"),
        DropDownMenu(option: "El Salvador"),
        DropDownMenu(option: "Equatorial Guinea"),
        DropDownMenu(option: "Eritrea"),
        DropDownMenu(option: "Estonia"),
        DropDownMenu(option: "Eswatini"),
        DropDownMenu(option: "Ethiopia"),
        DropDownMenu(option: "Fiji"),
        DropDownMenu(option: "Finland"),
        DropDownMenu(option: "France"),
        DropDownMenu(option: "Gabon"),
        DropDownMenu(option: "Gambia"),
        DropDownMenu(option: "Georgia"),
        DropDownMenu(option: "Germany"),
        DropDownMenu(option: "Ghana"),
        DropDownMenu(option: "Greece"),
        DropDownMenu(option: "Grenada"),
        DropDownMenu(option: "Guatemala"),
        DropDownMenu(option: "Guinea"),
        DropDownMenu(option: "Guinea-Bissau"),
        DropDownMenu(option: "Guyana"),
        DropDownMenu(option: "Haiti"),
        DropDownMenu(option: "Honduras"),
        DropDownMenu(option: "Hungary"),
        DropDownMenu(option: "Iceland"),
        DropDownMenu(option: "India"),
        DropDownMenu(option: "Indonesia"),
        DropDownMenu(option: "Iran"),
        DropDownMenu(option: "Iraq"),
        DropDownMenu(option: "Ireland"),
        DropDownMenu(option: "Israel"),
        DropDownMenu(option: "Italy"),
        DropDownMenu(option: "Ivory Coast"),
        DropDownMenu(option: "Jamaica"),
        DropDownMenu(option: "Japan"),
        DropDownMenu(option: "Jordan"),
        DropDownMenu(option: "Kazakhstan"),
        DropDownMenu(option: "Kenya"),
        DropDownMenu(option: "Kiribati"),
        DropDownMenu(option: "Kosovo"),
        DropDownMenu(option: "Kuwait"),
        DropDownMenu(option: "Kyrgyzstan"),
        DropDownMenu(option: "Laos"),
        DropDownMenu(option: "Latvia"),
        DropDownMenu(option: "Lebanon"),
        DropDownMenu(option: "Lesotho"),
        DropDownMenu(option: "Liberia"),
        DropDownMenu(option: "Libya"),
        DropDownMenu(option: "Liechtenstein"),
        DropDownMenu(option: "Lithuania"),
        DropDownMenu(option: "Luxembourg"),
        DropDownMenu(option: "Madagascar"),
        DropDownMenu(option: "Malawi"),
        DropDownMenu(option: "Malaysia"),
        DropDownMenu(option: "Maldives"),
        DropDownMenu(option: "Mali"),
        DropDownMenu(option: "Malta"),
        DropDownMenu(option: "Marshall Islands"),
        DropDownMenu(option: "Mauritania"),
        DropDownMenu(option: "Mauritius"),
        DropDownMenu(option: "Mexico"),
        DropDownMenu(option: "Micronesia"),
        DropDownMenu(option: "Moldova"),
        DropDownMenu(option: "Monaco"),
        DropDownMenu(option: "Mongolia"),
        DropDownMenu(option: "Montenegro"),
        DropDownMenu(option: "Morocco"),
        DropDownMenu(option: "Mozambique"),
        DropDownMenu(option: "Myanmar (Burma)"),
        DropDownMenu(option: "Namibia"),
        DropDownMenu(option: "Nauru"),
        DropDownMenu(option: "Nepal"),
        DropDownMenu(option: "Netherlands"),
        DropDownMenu(option: "New Zealand"),
        DropDownMenu(option: "Nicaragua"),
        DropDownMenu(option: "Niger"),
        DropDownMenu(option: "Nigeria"),
        DropDownMenu(option: "North Macedonia"),
        DropDownMenu(option: "Norway"),
        DropDownMenu(option: "Oman"),
        DropDownMenu(option: "Pakistan"),
        DropDownMenu(option: "Palau"),
        DropDownMenu(option: "Panama"),
        DropDownMenu(option: "Papua New Guinea"),
        DropDownMenu(option: "Paraguay"),
        DropDownMenu(option: "Peru"),
        DropDownMenu(option: "Philippines"),
        DropDownMenu(option: "Poland"),
        DropDownMenu(option: "Portugal"),
        DropDownMenu(option: "Qatar"),
        DropDownMenu(option: "Romania"),
        DropDownMenu(option: "Russia"),
        DropDownMenu(option: "Rwanda"),
        DropDownMenu(option: "Saint Kitts and Nevis"),
        DropDownMenu(option: "Saint Lucia"),
        DropDownMenu(option: "Saint Vincent and the Grenadines"),
        DropDownMenu(option: "Samoa"),
        DropDownMenu(option: "San Marino"),
        DropDownMenu(option: "Sao Tome and Principe"),
        DropDownMenu(option: "Saudi Arabia"),
        DropDownMenu(option: "Senegal"),
        DropDownMenu(option: "Serbia"),
        DropDownMenu(option: "Seychelles"),
        DropDownMenu(option: "Sierra Leone"),
        DropDownMenu(option: "Singapore"),
        DropDownMenu(option: "Slovakia"),
        DropDownMenu(option: "Slovenia"),
        DropDownMenu(option: "Solomon Islands"),
        DropDownMenu(option: "Somalia"),
        DropDownMenu(option: "South Africa"),
        DropDownMenu(option: "South Korea"),
        DropDownMenu(option: "South Sudan"),
        DropDownMenu(option: "Spain"),
        DropDownMenu(option: "Sri Lanka"),
        DropDownMenu(option: "Sudan"),
        DropDownMenu(option: "Suriname"),
        DropDownMenu(option: "Sweden"),
        DropDownMenu(option: "Switzerland"),
        DropDownMenu(option: "Syria"),
        DropDownMenu(option: "Taiwan"),
        DropDownMenu(option: "Tajikistan"),
        DropDownMenu(option: "Tanzania"),
        DropDownMenu(option: "Thailand"),
        DropDownMenu(option: "Togo"),
        DropDownMenu(option: "Tonga"),
        DropDownMenu(option: "Trinidad and Tobago"),
        DropDownMenu(option: "Tunisia"),
        DropDownMenu(option: "Turkey"),
        DropDownMenu(option: "Turkmenistan"),
        DropDownMenu(option: "Tuvalu"),
        DropDownMenu(option: "Uganda"),
        DropDownMenu(option: "Ukraine"),
        DropDownMenu(option: "United Arab Emirates"),
        DropDownMenu(option: "United Kingdom"),
        DropDownMenu(option: "United States of America"),
        DropDownMenu(option: "Uruguay"),
        DropDownMenu(option: "Uzbekistan"),
        DropDownMenu(option: "Vanuatu"),
        DropDownMenu(option: "Vatican City"),
        DropDownMenu(option: "Venezuela"),
        DropDownMenu(option: "Vietnam"),
        DropDownMenu(option: "Yemen"),
        DropDownMenu(option: "Zambia"),
        DropDownMenu(option: "Zimbabwe")
    
    ]
}
